baseURL = "https://oliverbenning.com"
title = "Oliver Benning"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
    author = "Oliver Benning"
    description = "Oliver Benning's personal website"
    keywords = "blog,developer,personal"
    info = "Full Stack Developer and Security Researcher"
    avatarURL = "/Oliver.png"
    footerContent = "Available for consulting at <a href='https://strikethrough.net'>strikethrough.net</a>."
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = true 
    hideCopyright = false
    since = 2019

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/obenn/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 2
    url = "https://twitter.com/OliverBenning/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
    name = "Mastodon"
    icon = "fa fa-mastodon"
    weight = 4
    url = "https://mastodon.social/@obenn"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 5
    url = "https://gitlab.com/obenn/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "https://oliverbenning.com/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "blog/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "CV"
            weight = 4
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.fr]
        languageName = "Français"
        title = "Oliver Benning"

        [languages.fr.params]
            author = "Oliver Benning"
            info = "Développeur Full Stack et rechercheur en sécurité"
            description = "Site personelle de Oliver Benning"
            keywords = "blog,developpeur,personelle"
            footerContent = "disponible pour consultation à <a href='https://strikethrough.net'>strikethrough.net</a>."

        [languages.fr.menu]

            [[languages.fr.menu.main]]
            name = "À propos"
            weight = 1
            url = "about/"

            [[languages.fr.menu.main]]
            name = "Blog"
            weight = 2
            url = "blog/"

            [[languages.fr.menu.main]]
            name = "Projets"
            weight = 3
            url = "projects/"

            [[languages.fr.menu.main]]
            name = "CV"
            weight = 4
            url = "cv/"

            [[languages.fr.menu.main]]
            name = "Contactez"
            weight = 5
            url = "contact/"
