baseurl: 'https://oliverbenning.com'
title: Oliver Benning
theme: hugo-coder
languagecode: en
defaultcontentlanguage: en
paginate: 20
pygmentsstyle: bw
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
params:
  author: Oliver Benning
  info: Full Stack Developer and Security Researcher
  description: Oliver Benning's personal website
  keywords: 'blog,developer,personal'
  gravatar: me@oliverbenning.com
  favicon_32: /img/favicon-32x32.png
  favicon_16: /img/favicon-16x16.png
  footercontent: >-
    Available for consulting at <a
    href='https://strikethrough.net'>strikethrough.net</a>.
  hideFooter: false
  hideCredits: true
  hideCopyright: false
  since: 2020
  enableTwemoji: true
  colorsheme: auto
  hidecolorschemetoggle: true
  social:
    - name: Github
      icon: fa fa-github fa-2x
      weight: 1
      url: 'https://github.com/obenn/'
    - name: LinkedIn
      icon: fa fa-linkedin fa-2x
      weight: 2
      url: 'https://linkedin.com/in/oliverbenning'
    - name: Twitter
      icon: fa fa-twitter fa-2x
      weight: 3
      url: 'https://twitter.com/OliverBenning/'
    - name: Mastodon
      icon: fa fa-mastodon fa-2x
      weight: 4
      url: 'https://mastodon.social/@obenn/'
    - name: Gitlab
      icon: fa fa-gitlab fa-2x
      weight: 5
      url: 'https://gitlab.com/obenn/'
    - name: RSS
      icon: fa fa-rss fa-2x
      weight: 6
      url: 'https://oliverbenning.com/index.xml'
      rel: alternate
      type: application/rss+xml
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    languageName: English
    menu:
      main:
        - name: Blog
          weight: 1
          url: posts/
        - name: About
          weight: 2
          url: about/
        - name: CV
          weight: 3
          url: cv/
  fr:
    languageName: Français
    title: Oliver Benning
    params:
      info: Développeur Full Stack et rechercheur en sécurité
      footercontent: >-
        disponible pour consultation à <a
        href='https://strikethrough.net'>strikethrough.net</a>.
    menu:
      main:
        - name: Blog
          weight: 1
          url: posts/
        - name: À propos
          weight: 2
          url: about/
        - name: CV 
          weight: 3
          url: cv/

